# Generated by Django 4.1.2 on 2022-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_caregiver',
            field=models.BooleanField(default=False),
        ),
    ]
