# Generated by Django 4.1.2 on 2022-11-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_application_location_alter_application_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
                ('location', models.TextField(blank=True, max_length=300, null=True)),
                ('timeStarted', models.DateTimeField()),
                ('timeEnded', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.BooleanField(default=False)),
                ('babysitter', models.BooleanField(default=False)),
                ('petcarer', models.BooleanField(default=False)),
                ('_caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
