# Generated by Django 4.1.2 on 2022-11-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to=users.models.imageUpload)),
                ('good_conduct', models.ImageField(blank=True, null=True, upload_to=users.models.imageUpload)),
                ('age', models.IntegerField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_babysitter', models.BooleanField(default=False)),
                ('is_petcarer', models.BooleanField(default=False)),
                ('is_cgiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
