# Generated by Django 4.1.2 on 2022-11-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
