# Generated by Django 4.1.2 on 2022-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_jobs__caregiver_jobs_c_giver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='timeEnded',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='timeStarted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
